// swift-tools-version: 5.9
import PackageDescription

// NavAI — on-device chat-suggestion engine (BitNet b1.58 via bitnet.cpp) plus
// the hybrid orchestrator that prefers the server when online and falls back to
// the on-device model (and finally templates) when offline.
//
// Layers:
//   NavAIPrompt  — pure Foundation: context model, prompt building, output
//                  parsing. No native/UI deps, so it's unit-testable on any host.
//   BitNetCore   — prebuilt bitnet.cpp static libs (run scripts/build-bitnet-ios.sh).
//   NavAI        — the engine (actor over BitNetCore), model download manager,
//                  and SuggestionEngine hybrid router.
let package = Package(
    name: "NavAI",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "NavAI", targets: ["NavAI"]),
        .library(name: "NavAIPrompt", targets: ["NavAIPrompt"]),
    ],
    dependencies: [
        .package(path: "../NavCore"),
        .package(path: "../NavNetworking"),
    ],
    targets: [
        // Pure, dependency-free logic — the part that's cheap to test.
        .target(name: "NavAIPrompt"),

        // Prebuilt bitnet.cpp (llama.cpp + ggml + nava_bitnet wrapper).
        // Generated by scripts/build-bitnet-ios.sh; not checked in.
        .binaryTarget(
            name: "BitNetCore",
            path: "Frameworks/BitNet.xcframework"
        ),

        .target(
            name: "NavAI",
            dependencies: [
                "NavAIPrompt",
                "BitNetCore",
                .product(name: "NavCore", package: "NavCore"),
                .product(name: "NavNetworking", package: "NavNetworking"),
            ]
        ),

        .testTarget(
            name: "NavAIPromptTests",
            dependencies: ["NavAIPrompt"]
        ),
    ]
)
